### ISSUE TITLE
Model performance

### ISSUE THREAD

**Issue by JackieZhangdx** [philferriere/tfwss#1]
Hi Phil,
Thanks a lot for sharing you code. 
1. I'm wondering the AP performance of your implementation, or could you please release trained model so that I can evaluate the results?
2.  It seems that the Grabcut masks are pre-computed and included in dataset you released. Are these masks generated from the code in "segment.py" ? How long does it take?
Many thanks.

**Comment by philferriere** [comment]
You're welcome, Jackie,

My answers below:

1/ If you're open to it, and are willing to help, I wouldn't mind adding a "validation" python notebook that measures the mAP. Feel free to submit a PR if you ever decide to implement this. A link to the pre-trained model (`vgg_16_4chan_weak.ckpt-50000`) can be found [here](http://bit.ly/tf-wss)

2/ The grabcut samples are generated in the `prepare()` method of the `BKVOCDataset` object:

``` python    
    ###
    ### Input Samples and Labels Prep
    ###
    def prepare(self):
        """Do all the preprocessing needed before training/val/test samples can be generated.
        """
        # Load image/mask pairs text file and the masks bbox info
        if not self._load_img_mask_pairs_file(self._img_mask_pairs_file):
            # Convert instance masks stored in .mat files to .png files and compute their bboxes
            self._mat_masks_to_png()
    
        # Generate grabcuts, if they don't exist yet
        self._bboxes_to_grabcuts()
    
        # Generate train and test image/mask pair files, if they don't exist yet
        self._split_img_mask_pairs()
```
And, yes, the `bboxes_to_grabcuts()` method uses the `grabcut()` function in `segment.py`

It's actually pretty fast (a matter of minutes on a modern PC)
