### ISSUE TITLE
img_mask_pairs.txt

### ISSUE THREAD

**Issue by dhpollack** [philferriere/tfwss#2]
I downloaded the benchmark dataset but I did not see the `img_mask_pairs.txt` file nor any want to generate it.  I suspect that I am simply missing something to generate it.  Could you provide some insight into how to generate (or download) that file?

**Comment by philferriere** [comment]
Hi @dhpollack ,

I've added (hopefully) clearer instructions [here](https://github.com/philferriere/tfwss/blob/master/README.md#link-to-pre-trained-model-and-bk-voc-data-files).

Let me know if you still have questions after this!

Cheers, -- Phil

**Comment by dhpollack** [comment]
@philferriere, your solution didn't work for me because the database didn't init correctly.  The initialization expects `img_mask_pairs.txt` to exist, but it doesn't exist until one runs prepare.  To avoid this catch 22, you can add a "prepare" phase which does not require that file like so...

```python
        # Init batch parameters
        if self._phase == 'train':
            self._load_img_mask_pairs_file(self._train_img_mask_pairs_file)
            self._grabcut_files = [self._grabcuts_folder + '/' + os.path.basename(img_mask_pair[1]) for img_mask_pair in self._img_mask_pairs]
            self._train_ptr = 0
            self.train_size = len(self._img_mask_pairs) if _DBG_TRAIN_SET == -1 else _DBG_TRAIN_SET
            self._train_idx = np.arange(self.train_size)
            np.random.seed(1)
            np.random.shuffle(self._train_idx)
        elif self._phase == "prepare":
            pass  # do nothing
        else:
            self._options['use_grabcut_labels'] = False
            self._load_img_mask_pairs_file(self._test_img_mask_pairs_file)
            self._test_ptr = 0
            self.test_size = len(self._img_mask_pairs)

...

if __name__ == '__main__':
    dataset = BKVOCDataset(phase="prepare")
    dataset.prepare()

```

**Comment by philferriere** [comment]
@dhpollack , I've updated `dataset.py` to check for the existence of the main database file and automatically generate all the intermediary files, if they do not exist already. Please let me know if that doesn't work for you or if you face additional issues.
